# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('query', models.TextField(verbose_name='query')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='last run')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'saved query',
                'verbose_name_plural': 'saved queries',
            },
        ),
    ]
